#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT(
    KC_Q, KC_W, KC_E, KC_R, KC_T,    KC_Y, KC_U, KC_I, KC_O, KC_P,
    LCTL_T(KC_A), LALT_T(KC_S), LGUI_T(KC_D), LSFT_T(KC_F), KC_G,    KC_H, RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN),
    KC_Z, KC_X, KC_C, KC_V, KC_B, DF(1),    LGUI(LSFT(KC_S)), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
    KC_NO, KC_NO, KC_NO, LT(6,KC_ESC), LT(2,KC_BSPC), LT(7,KC_VOLD),    LT(7,KC_VOLU), LT(4,KC_SPC), LT(5,KC_TAB), KC_NO, KC_NO, KC_NO
  ),
  [1] = LAYOUT(
    KC_Q, KC_W, KC_E, KC_R, KC_T,    KC_Y, KC_U, KC_I, KC_O, KC_P,
    LCTL_T(KC_A), LALT_T(KC_S), LGUI_T(KC_D), LSFT_T(KC_F), KC_G,    KC_H, RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L), RCTL_T(KC_SCLN),
    KC_Z, KC_X, KC_C, KC_V, KC_B, DF(0),    LCTL(LGUI(LSFT(KC_4))), KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
    KC_NO, KC_NO, KC_NO, LT(6,KC_ESC), LT(3,KC_BSPC), LT(7,KC_VOLD),    LT(7,KC_VOLU), LT(4,KC_SPC), LT(5,KC_TAB), KC_NO, KC_NO, KC_NO
  ),
  [2] = LAYOUT(
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    LCTL(LSFT(KC_TAB)), LALT(KC_ESC), RCS(KC_J), LCTL(KC_TAB), LCTL(KC_LBRC),
    KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO,    KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, LCTL(KC_RBRC),
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    KC_DEL, KC_P7, KC_P3, KC_P9, KC_P1, KC_CAPS,
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BRID,    KC_BRIU, KC_ENT, KC_MINS, KC_NO, KC_NO, KC_NO
  ),
  [3] = LAYOUT(
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    LCTL(LSFT(KC_TAB)), LGUI(KC_GRV), LGUI(LALT(KC_J)), LCTL(KC_TAB), LGUI(KC_LBRC),
    KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO,    KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, LGUI(KC_RBRC),
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    KC_DEL, KC_P7, KC_P3, KC_P9, KC_P1, KC_CAPS,
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BRID,    KC_BRIU, KC_ENT, KC_MINS, KC_NO, KC_NO, KC_NO
  ),
  [4] = LAYOUT(
    KC_LCBR, KC_AMPR, KC_ASTR, KC_LPRN, KC_RCBR,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_DQUO, KC_DLR, KC_PERC, KC_CIRC, KC_PLUS,    KC_NO, KC_RSFT, KC_RGUI, KC_RALT, KC_RCTL,
    KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_PIPE, KC_NO,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_NO, KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_UNDS,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  ),
  [5] = LAYOUT(
    KC_LBRC, KC_7, KC_8, KC_9, KC_RBRC,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_QUOT, KC_4, KC_5, KC_6, KC_EQL,    KC_NO, KC_RSFT, KC_RGUI, KC_RALT, KC_RCTL,
    KC_GRV, KC_1, KC_2, KC_3, KC_BSLS, KC_NO,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_NO, KC_NO, KC_NO, KC_DOT, KC_0, KC_MINS,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  ),
  [6] = LAYOUT(
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, KC_NO,    KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_ACL0,
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    KC_NO, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, KC_ACL1,
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,    KC_BTN3, KC_BTN1, KC_BTN2, KC_NO, KC_NO, KC_NO
  ),
  [7] = LAYOUT(
    KC_NO, KC_F7, KC_F8, KC_F9, KC_F10,    DF(0), KC_NO, KC_NO, KC_NO, DF(1),
    KC_NO, KC_F4, KC_F5, KC_F6, KC_F11,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_NO, KC_F1, KC_F2, KC_F3, KC_F12, KC_NO,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PSCR,    KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  )
};
